-- -------------------------------------------------------------
-- 
-- File Name: /home/aluno/Documentos/PSD/PF/hdl_IIRn8Gzerofixed/hdlsrc/PF/DUT.vhd
-- Created: 2020-08-11 12:56:59
-- 
-- Generated by MATLAB 8.5 and HDL Coder 3.6
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.000125
-- Target subsystem base rate: 0.000125
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0.000125
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Y                             ce_out        0.000125
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: DUT
-- Source Path: PF/DUT
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY DUT IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        X                                 :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        ce_out                            :   OUT   std_logic;
        Y                                 :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En11
        );
END DUT;


ARCHITECTURE rtl OF DUT IS

  -- Component Declarations
  COMPONENT IIRn8GzerosQTZSOBE11bits
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Input                           :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          Output                          :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En11
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : IIRn8GzerosQTZSOBE11bits
    USE ENTITY work.IIRn8GzerosQTZSOBE11bits(rtl);

  -- Signals
  SIGNAL IIRn8GzerosQTZSOBE11bits_out1    : std_logic_vector(15 DOWNTO 0);  -- ufix16

BEGIN
  -- Com quantizacao
  -- 
  -- Sem quantizacao

  u_IIRn8GzerosQTZSOBE11bits : IIRn8GzerosQTZSOBE11bits
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              Input => X,  -- sfix16_En15
              Output => IIRn8GzerosQTZSOBE11bits_out1  -- sfix16_En11
              );

  ce_out <= clk_enable;

  Y <= IIRn8GzerosQTZSOBE11bits_out1;

END rtl;

