-- -------------------------------------------------------------
-- 
-- File Name: /home/aluno/Documentos/PSD/PF/hdl_IIRn8Gzerofixed/hdlsrc/PF/IIRn8GzerosQTZSOBE11bits.vhd
-- Created: 2020-08-11 12:56:59
-- 
-- Generated by MATLAB 8.5 and HDL Coder 3.6
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: IIRn8GzerosQTZSOBE11bits
-- Source Path: PF/DUT/IIRn8GzerosQTZSOBE11bits
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY IIRn8GzerosQTZSOBE11bits IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        Input                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        Output                            :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En11
        );
END IIRn8GzerosQTZSOBE11bits;


ARCHITECTURE rtl OF IIRn8GzerosQTZSOBE11bits IS

  -- Signals
  SIGNAL Input_signed                     : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL s_1_mul_temp                     : signed(26 DOWNTO 0);  -- sfix27_En28
  SIGNAL s_1_out1                         : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL b_2_1_out1                       : signed(26 DOWNTO 0);  -- sfix27_En24
  SIGNAL b_3_1_out1                       : signed(26 DOWNTO 0);  -- sfix27_En24
  SIGNAL CastStageOutput1_out1            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL a_2_1_out1                       : signed(26 DOWNTO 0);  -- sfix27_En24
  SIGNAL a_3_1_out1                       : signed(26 DOWNTO 0);  -- sfix27_En24
  SIGNAL FootSum1_sub_cast                : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL FootSum1_sub_cast_1              : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL FootSum1_out1                    : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL CastFootStates1_out1             : signed(15 DOWNTO 0);  -- sfix16_En11
  SIGNAL FootDelay1_out1                  : signed(15 DOWNTO 0);  -- sfix16_En11
  SIGNAL BodyLSum21_add_cast              : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL BodyLSum21_add_cast_1            : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL BodyLSum21_out1                  : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL BodyRSum21_sub_cast              : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL BodyRSum21_out1                  : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL CastStates1_out1                 : signed(15 DOWNTO 0);  -- sfix16_En11
  SIGNAL BodyDelay21_out1                 : signed(15 DOWNTO 0);  -- sfix16_En11
  SIGNAL HeadSum1_add_cast                : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL HeadSum1_add_cast_1              : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL HeadSum1_out1                    : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL b_2_2_out1                       : signed(26 DOWNTO 0);  -- sfix27_En24
  SIGNAL b_3_2_out1                       : signed(26 DOWNTO 0);  -- sfix27_En24
  SIGNAL CastStageOutput2_out1            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL a_2_2_out1                       : signed(26 DOWNTO 0);  -- sfix27_En24
  SIGNAL a_3_2_out1                       : signed(26 DOWNTO 0);  -- sfix27_En24
  SIGNAL FootSum2_sub_cast                : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL FootSum2_sub_cast_1              : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL FootSum2_out1                    : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL CastFootStates2_out1             : signed(15 DOWNTO 0);  -- sfix16_En11
  SIGNAL FootDelay2_out1                  : signed(15 DOWNTO 0);  -- sfix16_En11
  SIGNAL BodyLSum22_add_cast              : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL BodyLSum22_add_cast_1            : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL BodyLSum22_out1                  : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL BodyRSum22_sub_cast              : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL BodyRSum22_out1                  : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL CastStates2_out1                 : signed(15 DOWNTO 0);  -- sfix16_En11
  SIGNAL BodyDelay22_out1                 : signed(15 DOWNTO 0);  -- sfix16_En11
  SIGNAL HeadSum2_add_cast                : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL HeadSum2_add_cast_1              : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL HeadSum2_out1                    : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL b_2_3_out1                       : signed(26 DOWNTO 0);  -- sfix27_En24
  SIGNAL b_3_3_out1                       : signed(26 DOWNTO 0);  -- sfix27_En24
  SIGNAL CastStageOutput3_out1            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL a_2_3_out1                       : signed(26 DOWNTO 0);  -- sfix27_En24
  SIGNAL a_3_3_out1                       : signed(26 DOWNTO 0);  -- sfix27_En24
  SIGNAL FootSum3_sub_cast                : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL FootSum3_sub_cast_1              : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL FootSum3_out1                    : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL CastFootStates3_out1             : signed(15 DOWNTO 0);  -- sfix16_En11
  SIGNAL FootDelay3_out1                  : signed(15 DOWNTO 0);  -- sfix16_En11
  SIGNAL BodyLSum23_add_cast              : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL BodyLSum23_add_cast_1            : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL BodyLSum23_out1                  : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL BodyRSum23_sub_cast              : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL BodyRSum23_out1                  : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL CastStates3_out1                 : signed(15 DOWNTO 0);  -- sfix16_En11
  SIGNAL BodyDelay23_out1                 : signed(15 DOWNTO 0);  -- sfix16_En11
  SIGNAL HeadSum3_add_cast                : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL HeadSum3_add_cast_1              : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL HeadSum3_out1                    : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL b_2_4_out1                       : signed(26 DOWNTO 0);  -- sfix27_En24
  SIGNAL b_3_4_out1                       : signed(26 DOWNTO 0);  -- sfix27_En24
  SIGNAL CastStageOutput4_out1            : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL a_2_4_out1                       : signed(26 DOWNTO 0);  -- sfix27_En24
  SIGNAL a_3_4_out1                       : signed(26 DOWNTO 0);  -- sfix27_En24
  SIGNAL FootSum4_sub_cast                : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL FootSum4_sub_cast_1              : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL FootSum4_out1                    : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL CastFootStates4_out1             : signed(15 DOWNTO 0);  -- sfix16_En11
  SIGNAL FootDelay4_out1                  : signed(15 DOWNTO 0);  -- sfix16_En11
  SIGNAL BodyLSum24_add_cast              : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL BodyLSum24_add_cast_1            : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL BodyLSum24_out1                  : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL BodyRSum24_sub_cast              : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL BodyRSum24_out1                  : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL CastStates4_out1                 : signed(15 DOWNTO 0);  -- sfix16_En11
  SIGNAL BodyDelay24_out1                 : signed(15 DOWNTO 0);  -- sfix16_En11
  SIGNAL HeadSum4_add_cast                : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL HeadSum4_add_cast_1              : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL HeadSum4_out1                    : signed(39 DOWNTO 0);  -- sfix40_En24
  SIGNAL ConvertOut_out1                  : signed(15 DOWNTO 0);  -- sfix16_En11

BEGIN
  Input_signed <= signed(Input);

  s_1_mul_temp <= to_signed(16#212#, 11) * Input_signed;
  s_1_out1 <= (resize(s_1_mul_temp(26 DOWNTO 13), 16)) + ('0' & (s_1_mul_temp(12) AND (s_1_mul_temp(13) OR (s_1_mul_temp(11) OR s_1_mul_temp(10) OR s_1_mul_temp(9) OR s_1_mul_temp(8) OR s_1_mul_temp(7) OR s_1_mul_temp(6) OR s_1_mul_temp(5) OR s_1_mul_temp(4) OR s_1_mul_temp(3) OR s_1_mul_temp(2) OR s_1_mul_temp(1) OR s_1_mul_temp(0)))));

  b_2_1_out1 <= to_signed(-16#3A6#, 11) * s_1_out1;

  b_3_1_out1 <= resize(s_1_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 27);

  a_2_1_out1 <= to_signed(16#012#, 11) * CastStageOutput1_out1;

  a_3_1_out1 <= to_signed(16#073#, 11) * CastStageOutput1_out1;

  FootSum1_sub_cast <= resize(b_3_1_out1, 40);
  FootSum1_sub_cast_1 <= resize(a_3_1_out1, 40);
  FootSum1_out1 <= FootSum1_sub_cast - FootSum1_sub_cast_1;

  CastFootStates1_out1 <= FootSum1_out1(28 DOWNTO 13) + ('0' & (FootSum1_out1(12) AND (FootSum1_out1(13) OR (FootSum1_out1(11) OR FootSum1_out1(10) OR FootSum1_out1(9) OR FootSum1_out1(8) OR FootSum1_out1(7) OR FootSum1_out1(6) OR FootSum1_out1(5) OR FootSum1_out1(4) OR FootSum1_out1(3) OR FootSum1_out1(2) OR FootSum1_out1(1) OR FootSum1_out1(0)))));

  FootDelay1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      FootDelay1_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        FootDelay1_out1 <= CastFootStates1_out1;
      END IF;
    END IF;
  END PROCESS FootDelay1_process;


  BodyLSum21_add_cast <= resize(b_2_1_out1, 40);
  BodyLSum21_add_cast_1 <= resize(FootDelay1_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);
  BodyLSum21_out1 <= BodyLSum21_add_cast + BodyLSum21_add_cast_1;

  BodyRSum21_sub_cast <= resize(a_2_1_out1, 40);
  BodyRSum21_out1 <= BodyLSum21_out1 - BodyRSum21_sub_cast;

  CastStates1_out1 <= BodyRSum21_out1(28 DOWNTO 13) + ('0' & (BodyRSum21_out1(12) AND (BodyRSum21_out1(13) OR (BodyRSum21_out1(11) OR BodyRSum21_out1(10) OR BodyRSum21_out1(9) OR BodyRSum21_out1(8) OR BodyRSum21_out1(7) OR BodyRSum21_out1(6) OR BodyRSum21_out1(5) OR BodyRSum21_out1(4) OR BodyRSum21_out1(3) OR BodyRSum21_out1(2) OR BodyRSum21_out1(1) OR BodyRSum21_out1(0)))));

  BodyDelay21_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      BodyDelay21_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        BodyDelay21_out1 <= CastStates1_out1;
      END IF;
    END IF;
  END PROCESS BodyDelay21_process;


  HeadSum1_add_cast <= resize(s_1_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);
  HeadSum1_add_cast_1 <= resize(BodyDelay21_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);
  HeadSum1_out1 <= HeadSum1_add_cast + HeadSum1_add_cast_1;

  CastStageOutput1_out1 <= HeadSum1_out1(24 DOWNTO 9) + ('0' & (HeadSum1_out1(8) AND (HeadSum1_out1(9) OR (HeadSum1_out1(7) OR HeadSum1_out1(6) OR HeadSum1_out1(5) OR HeadSum1_out1(4) OR HeadSum1_out1(3) OR HeadSum1_out1(2) OR HeadSum1_out1(1) OR HeadSum1_out1(0)))));

  b_2_2_out1 <= to_signed(16#3F0#, 11) * CastStageOutput1_out1;

  b_3_2_out1 <= resize(CastStageOutput1_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 27);

  a_2_2_out1 <= to_signed(16#1E7#, 11) * CastStageOutput2_out1;

  a_3_2_out1 <= to_signed(16#0BF#, 11) * CastStageOutput2_out1;

  FootSum2_sub_cast <= resize(b_3_2_out1, 40);
  FootSum2_sub_cast_1 <= resize(a_3_2_out1, 40);
  FootSum2_out1 <= FootSum2_sub_cast - FootSum2_sub_cast_1;

  CastFootStates2_out1 <= FootSum2_out1(28 DOWNTO 13) + ('0' & (FootSum2_out1(12) AND (FootSum2_out1(13) OR (FootSum2_out1(11) OR FootSum2_out1(10) OR FootSum2_out1(9) OR FootSum2_out1(8) OR FootSum2_out1(7) OR FootSum2_out1(6) OR FootSum2_out1(5) OR FootSum2_out1(4) OR FootSum2_out1(3) OR FootSum2_out1(2) OR FootSum2_out1(1) OR FootSum2_out1(0)))));

  FootDelay2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      FootDelay2_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        FootDelay2_out1 <= CastFootStates2_out1;
      END IF;
    END IF;
  END PROCESS FootDelay2_process;


  BodyLSum22_add_cast <= resize(b_2_2_out1, 40);
  BodyLSum22_add_cast_1 <= resize(FootDelay2_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);
  BodyLSum22_out1 <= BodyLSum22_add_cast + BodyLSum22_add_cast_1;

  BodyRSum22_sub_cast <= resize(a_2_2_out1, 40);
  BodyRSum22_out1 <= BodyLSum22_out1 - BodyRSum22_sub_cast;

  CastStates2_out1 <= BodyRSum22_out1(28 DOWNTO 13) + ('0' & (BodyRSum22_out1(12) AND (BodyRSum22_out1(13) OR (BodyRSum22_out1(11) OR BodyRSum22_out1(10) OR BodyRSum22_out1(9) OR BodyRSum22_out1(8) OR BodyRSum22_out1(7) OR BodyRSum22_out1(6) OR BodyRSum22_out1(5) OR BodyRSum22_out1(4) OR BodyRSum22_out1(3) OR BodyRSum22_out1(2) OR BodyRSum22_out1(1) OR BodyRSum22_out1(0)))));

  BodyDelay22_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      BodyDelay22_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        BodyDelay22_out1 <= CastStates2_out1;
      END IF;
    END IF;
  END PROCESS BodyDelay22_process;


  HeadSum2_add_cast <= resize(CastStageOutput1_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);
  HeadSum2_add_cast_1 <= resize(BodyDelay22_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);
  HeadSum2_out1 <= HeadSum2_add_cast + HeadSum2_add_cast_1;

  CastStageOutput2_out1 <= HeadSum2_out1(24 DOWNTO 9) + ('0' & (HeadSum2_out1(8) AND (HeadSum2_out1(9) OR (HeadSum2_out1(7) OR HeadSum2_out1(6) OR HeadSum2_out1(5) OR HeadSum2_out1(4) OR HeadSum2_out1(3) OR HeadSum2_out1(2) OR HeadSum2_out1(1) OR HeadSum2_out1(0)))));

  b_2_3_out1 <= to_signed(-16#284#, 11) * CastStageOutput2_out1;

  b_3_3_out1 <= resize(CastStageOutput2_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 27);

  a_2_3_out1 <= to_signed(-16#098#, 11) * CastStageOutput3_out1;

  a_3_3_out1 <= to_signed(16#15C#, 11) * CastStageOutput3_out1;

  FootSum3_sub_cast <= resize(b_3_3_out1, 40);
  FootSum3_sub_cast_1 <= resize(a_3_3_out1, 40);
  FootSum3_out1 <= FootSum3_sub_cast - FootSum3_sub_cast_1;

  CastFootStates3_out1 <= FootSum3_out1(28 DOWNTO 13) + ('0' & (FootSum3_out1(12) AND (FootSum3_out1(13) OR (FootSum3_out1(11) OR FootSum3_out1(10) OR FootSum3_out1(9) OR FootSum3_out1(8) OR FootSum3_out1(7) OR FootSum3_out1(6) OR FootSum3_out1(5) OR FootSum3_out1(4) OR FootSum3_out1(3) OR FootSum3_out1(2) OR FootSum3_out1(1) OR FootSum3_out1(0)))));

  FootDelay3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      FootDelay3_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        FootDelay3_out1 <= CastFootStates3_out1;
      END IF;
    END IF;
  END PROCESS FootDelay3_process;


  BodyLSum23_add_cast <= resize(b_2_3_out1, 40);
  BodyLSum23_add_cast_1 <= resize(FootDelay3_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);
  BodyLSum23_out1 <= BodyLSum23_add_cast + BodyLSum23_add_cast_1;

  BodyRSum23_sub_cast <= resize(a_2_3_out1, 40);
  BodyRSum23_out1 <= BodyLSum23_out1 - BodyRSum23_sub_cast;

  CastStates3_out1 <= BodyRSum23_out1(28 DOWNTO 13) + ('0' & (BodyRSum23_out1(12) AND (BodyRSum23_out1(13) OR (BodyRSum23_out1(11) OR BodyRSum23_out1(10) OR BodyRSum23_out1(9) OR BodyRSum23_out1(8) OR BodyRSum23_out1(7) OR BodyRSum23_out1(6) OR BodyRSum23_out1(5) OR BodyRSum23_out1(4) OR BodyRSum23_out1(3) OR BodyRSum23_out1(2) OR BodyRSum23_out1(1) OR BodyRSum23_out1(0)))));

  BodyDelay23_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      BodyDelay23_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        BodyDelay23_out1 <= CastStates3_out1;
      END IF;
    END IF;
  END PROCESS BodyDelay23_process;


  HeadSum3_add_cast <= resize(CastStageOutput2_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);
  HeadSum3_add_cast_1 <= resize(BodyDelay23_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);
  HeadSum3_out1 <= HeadSum3_add_cast + HeadSum3_add_cast_1;

  CastStageOutput3_out1 <= HeadSum3_out1(24 DOWNTO 9) + ('0' & (HeadSum3_out1(8) AND (HeadSum3_out1(9) OR (HeadSum3_out1(7) OR HeadSum3_out1(6) OR HeadSum3_out1(5) OR HeadSum3_out1(4) OR HeadSum3_out1(3) OR HeadSum3_out1(2) OR HeadSum3_out1(1) OR HeadSum3_out1(0)))));

  b_2_4_out1 <= to_signed(16#3B3#, 11) * CastStageOutput3_out1;

  b_3_4_out1 <= resize(CastStageOutput3_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 27);

  a_2_4_out1 <= to_signed(16#2CE#, 11) * CastStageOutput4_out1;

  a_3_4_out1 <= to_signed(16#192#, 11) * CastStageOutput4_out1;

  FootSum4_sub_cast <= resize(b_3_4_out1, 40);
  FootSum4_sub_cast_1 <= resize(a_3_4_out1, 40);
  FootSum4_out1 <= FootSum4_sub_cast - FootSum4_sub_cast_1;

  CastFootStates4_out1 <= FootSum4_out1(28 DOWNTO 13) + ('0' & (FootSum4_out1(12) AND (FootSum4_out1(13) OR (FootSum4_out1(11) OR FootSum4_out1(10) OR FootSum4_out1(9) OR FootSum4_out1(8) OR FootSum4_out1(7) OR FootSum4_out1(6) OR FootSum4_out1(5) OR FootSum4_out1(4) OR FootSum4_out1(3) OR FootSum4_out1(2) OR FootSum4_out1(1) OR FootSum4_out1(0)))));

  FootDelay4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      FootDelay4_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        FootDelay4_out1 <= CastFootStates4_out1;
      END IF;
    END IF;
  END PROCESS FootDelay4_process;


  BodyLSum24_add_cast <= resize(b_2_4_out1, 40);
  BodyLSum24_add_cast_1 <= resize(FootDelay4_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);
  BodyLSum24_out1 <= BodyLSum24_add_cast + BodyLSum24_add_cast_1;

  BodyRSum24_sub_cast <= resize(a_2_4_out1, 40);
  BodyRSum24_out1 <= BodyLSum24_out1 - BodyRSum24_sub_cast;

  CastStates4_out1 <= BodyRSum24_out1(28 DOWNTO 13) + ('0' & (BodyRSum24_out1(12) AND (BodyRSum24_out1(13) OR (BodyRSum24_out1(11) OR BodyRSum24_out1(10) OR BodyRSum24_out1(9) OR BodyRSum24_out1(8) OR BodyRSum24_out1(7) OR BodyRSum24_out1(6) OR BodyRSum24_out1(5) OR BodyRSum24_out1(4) OR BodyRSum24_out1(3) OR BodyRSum24_out1(2) OR BodyRSum24_out1(1) OR BodyRSum24_out1(0)))));

  BodyDelay24_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      BodyDelay24_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        BodyDelay24_out1 <= CastStates4_out1;
      END IF;
    END IF;
  END PROCESS BodyDelay24_process;


  HeadSum4_add_cast <= resize(CastStageOutput3_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);
  HeadSum4_add_cast_1 <= resize(BodyDelay24_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);
  HeadSum4_out1 <= HeadSum4_add_cast + HeadSum4_add_cast_1;

  CastStageOutput4_out1 <= HeadSum4_out1(24 DOWNTO 9) + ('0' & (HeadSum4_out1(8) AND (HeadSum4_out1(9) OR (HeadSum4_out1(7) OR HeadSum4_out1(6) OR HeadSum4_out1(5) OR HeadSum4_out1(4) OR HeadSum4_out1(3) OR HeadSum4_out1(2) OR HeadSum4_out1(1) OR HeadSum4_out1(0)))));

  ConvertOut_out1 <= (resize(CastStageOutput4_out1(15 DOWNTO 4), 16)) + ('0' & (CastStageOutput4_out1(3) AND (CastStageOutput4_out1(4) OR (CastStageOutput4_out1(2) OR CastStageOutput4_out1(1) OR CastStageOutput4_out1(0)))));

  Output <= std_logic_vector(ConvertOut_out1);

END rtl;

