-- -------------------------------------------------------------
-- 
-- File Name: /home/aluno/Documentos/PSD/PF/hdl_FIRn15fixed/hdlsrc/PF/DUT.vhd
-- Created: 2020-08-11 08:06:43
-- 
-- Generated by MATLAB 8.5 and HDL Coder 3.6
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.000125
-- Target subsystem base rate: 0.000125
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0.000125
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Y                             ce_out        0.000125
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: DUT
-- Source Path: PF/DUT
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY DUT IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        X                                 :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        ce_out                            :   OUT   std_logic;
        Y                                 :   OUT   std_logic_vector(27 DOWNTO 0)  -- sfix28_En23
        );
END DUT;


ARCHITECTURE rtl OF DUT IS

  -- Component Declarations
  COMPONENT FIRn15QTZ11b
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Input                           :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          Output                          :   OUT   std_logic_vector(27 DOWNTO 0)  -- sfix28_En23
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : FIRn15QTZ11b
    USE ENTITY work.FIRn15QTZ11b(rtl);

  -- Signals
  SIGNAL FIRn15QTZ11b_out1                : std_logic_vector(27 DOWNTO 0);  -- ufix28

BEGIN
  -- Com quantizacao
  -- 
  -- Sem quantizacao

  u_FIRn15QTZ11b : FIRn15QTZ11b
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              Input => X,  -- sfix16_En15
              Output => FIRn15QTZ11b_out1  -- sfix28_En23
              );

  ce_out <= clk_enable;

  Y <= FIRn15QTZ11b_out1;

END rtl;

