-- -------------------------------------------------------------
--
-- Module: DUT_tb_data
-- Path: /home/aluno/Documentos/PSD/PF/hdl_FIRn15fixed/hdlsrc/PF
-- Created: 2020-08-11 08:07:09
-- Generated by MATLAB 8.5 and HDL Coder 3.6
-- Description: test bench data package
--
--
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;
USE work.DUT_tb_pkg.ALL;

PACKAGE DUT_tb_data IS


END DUT_tb_data;

PACKAGE BODY DUT_tb_data IS

END DUT_tb_data;
